build: off

os: unstable

skip_tags: true

environment:
  GH_TOKEN:
      secure: kzMnHRuGCZghNhoPietjDsKPdFKvwoHn3f8hXpRfV+0F0CnsIDe+im2ZO/bdC+En
  matrix:
    - nodejs_version: "6"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - yarn

test_script:
  - yarn versions
  - yarn test

build_script:
  - yarn electron-builder install-app-deps
  - yarn release
