build: off

os: unstable

skip_tags: true

environment:
  matrix:
    - nodejs_version: "6"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm
  - yarn
  - yarn electron-builder install-app-deps

test_script:
  - yarn versions
  - yarn test

build_script:
  - yarn build
  - yarn dist
