import {foundation, stone, shadows, windowColor, offwhite, blue, red, orange, purple} from './materials.js';

export default (scene) => {
  var shop = new THREE.Group()
  var shopBase = new THREE.Geometry()

// Foundation
  var bottom = new THREE.BoxGeometry(10, 1, 5)
  shopBase.merge(bottom)
  var bottomStair = new THREE.BoxGeometry(2, .5, .5)
  bottomStair.translate(0, .25, 2.75)
  shopBase.merge(bottomStair)
  var topStair = new THREE.BoxGeometry(2, .5, 1)
  topStair.translate(0, -.25, 3)
  shopBase.merge(topStair)
  var building = new THREE.Mesh(shopBase, foundation)
	building.castShadow = true
  shop.add(building)

// Building
  var glass = new THREE.BoxGeometry(9.75, 4.9, .125)
  glass.translate(0, 3, 2.4)
  var windows = new THREE.Mesh(glass, windowColor)
  shop.add(windows)
  var shopCore = new THREE.Geometry()
  var bottomFront = new THREE.BoxGeometry(4, 1, .75)
  bottomFront.translate(-3, 1, 2.125)
  shopCore.merge(bottomFront)
  bottomFront.translate(6, 0, 0)
  shopCore.merge(bottomFront)
  var topFront = new THREE.BoxGeometry(10, 1.5, .5)
  topFront.translate(0, 4.75, 2.25)
  shopCore.merge(topFront)
  var sides = new THREE.BoxGeometry(1, 5, 5)
  sides.translate(-4.5, 3, 0)
  shopCore.merge(sides)
  sides.translate(9, 0, 0)
  shopCore.merge(sides)
  var inner = new THREE.BoxGeometry(1, 2.5, .5)
  inner.translate(-1.5, 2.75, 2.25)
  shopCore.merge(inner)
  inner.translate(3, 0, 0)
  shopCore.merge(inner)
  var center = new THREE.BoxGeometry(10, 5, 1)
  center.translate(0, 3, -2)
  shopCore.merge(center)
  var top = new THREE.BoxGeometry(10, 2, 5)
  top.translate(0, 5, 0)
  shopCore.merge(top)
  var building = new THREE.Mesh(shopCore, stone)
	building.castShadow = true
  shop.add(building)
  var shopShadowGeometry = new THREE.Geometry()
  var coreShopShadow = shopCore.clone()
  var shopStepsShadow = shopBase.clone()
  shopShadowGeometry.merge(coreShopShadow)
  shopShadowGeometry.merge(shopStepsShadow)
  var shopShadow = new THREE.Mesh(shopShadowGeometry, shadows)
  shopShadow.receiveShadow = true
  shop.add(shopShadow)

// Insides
  var counter = new THREE.BoxGeometry(3, 1.5, 1)
  counter.translate(0, 1.25, 0)
  var Counters = new THREE.Mesh(counter, stone)
  shop.add(Counters)

  var shelf = new THREE.BoxGeometry(.5, .1, 3)
  shelf.translate(3.75, 2, 0)
  var shelf2 = new THREE.BoxGeometry(.5, .1, 3)
  shelf2.translate(3.75, 3, 0)
  shelf.merge(shelf2)
  shelf2.translate(0, 1, 0)
  shelf.merge(shelf2)
  shelf2.translate(-7.5, 0, 0)
  shelf.merge(shelf2)
  shelf2.translate(0, -1, 0)
  shelf.merge(shelf2)
  shelf2.translate(0, -1, 0)
  shelf.merge(shelf2)
  var shelves = new THREE.Mesh(shelf, stone)
  shop.add(shelves)

  var surfaceShadows = new THREE.Geometry()
  var counterShadows = counter.clone(true)
  surfaceShadows.merge(counterShadows)
  var shelfShadows = shelf.clone(true)
  surfaceShadows.merge(shelfShadows)
  var surfaceInteriorShadows = new THREE.Mesh(surfaceShadows, shadows)
  surfaceInteriorShadows.receiveShadow = true
  shop.add(surfaceInteriorShadows)

  var book1 = new THREE.BoxGeometry(.7, .75, .2)
  book1.translate(3.75, 3.45, 0)
  var book2 = new THREE.BoxGeometry(.7, .75, .2)
  book2.translate(3.75, 3.45, 1)
  book1.merge(book2)
  book2.translate(0, 1, -1.5)
  book1.merge(book2)
  book2.translate(0, -2, -.5)
  book1.merge(book2)
  book2.translate(0, 0, .75)
  book1.merge(book2)
  book2.translate(0, 0, 1)
  book1.merge(book2)
  book2.translate(-7.5, 0, 0)
  book1.merge(book2)
  book2.translate(0, 0, -1.5)
  book1.merge(book2)
  book2.translate(0, 1, .5)
  book1.merge(book2)
  book2.translate(0, 0, .75)
  book1.merge(book2)
  book2.translate(0, 1, .25)
  book1.merge(book2)
  book2.translate(0, 0, -.75)
  book1.merge(book2)
  book2.translate(0, 0, -.5)
  book1.merge(book2)
  var book7 = new THREE.BoxGeometry(.7, .75, .2)
  book7.translate(-3.5, 1.87, 2.25)
  book1.merge(book7)
  var redBooks = new THREE.Mesh(book1, red)
  redBooks.castShadow = true
  shop.add(redBooks)

  var books2 = new THREE.Geometry()
  var book3 = new THREE.BoxGeometry(.7, .75, .2)
  book3.translate(3.75, 3.45, 1.2)
  books2.merge(book3)
  book3.translate(0, 1, -1.5)
  books2.merge(book3)
  book3.translate(0, -2, -.5)
  books2.merge(book3)
  book3.translate(0, 0, .75)
  books2.merge(book3)
  book3.translate(0, 0, 1)
  books2.merge(book3)
  book3.translate(-7.5, 0, 0)
  books2.merge(book3)
  book3.translate(0, 0, -1.5)
  books2.merge(book3)
  book3.translate(0, 1, .5)
  books2.merge(book3)
  book3.translate(0, 0, .75)
  books2.merge(book3)
  book3.translate(0, 1, .25)
  books2.merge(book3)
  book3.translate(0, 0, -.75)
  books2.merge(book3)
  book3.translate(0, 0, -.5)
  books2.merge(book3)
  var book8 = new THREE.BoxGeometry(.7, .75, .2)
  book8.translate(-2.5, 1.87, 2.25)
  books2.merge(book8)
  var blueBooks = new THREE.Mesh(books2, blue)
  blueBooks.castShadow = true
  shop.add(blueBooks)

  var books3 = new THREE.Geometry()
  var book4 = new THREE.BoxGeometry(.7, .75, .2)
  book4.translate(3.75, 3.45, 1.4)
  books3.merge(book4)
  book4.translate(0, 1, -1.5)
  books3.merge(book4)
  book4.translate(0, -2, -.5)
  books3.merge(book4)
  book4.translate(0, 0, .75)
  books3.merge(book4)
  book4.translate(0, 0, 1)
  books3.merge(book4)
  book4.translate(-7.5, 0, 0)
  books3.merge(book4)
  book4.translate(0, 0, -1.5)
  books3.merge(book4)
  book4.translate(0, 1, .5)
  books3.merge(book4)
  book4.translate(0, 0, .75)
  books3.merge(book4)
  book4.translate(0, 1, .25)
  books3.merge(book4)
  book4.translate(0, 0, -.75)
  books3.merge(book4)
  book4.translate(0, 0, -1.5)
  books3.merge(book4)
  book4.translate(7.5, 0, 2)
  books3.merge(book4)
  book4.translate(0, -1, -1.75)
  books3.merge(book4)
  var purpleBooks = new THREE.Mesh(books3, purple)
  purpleBooks.castShadow = true
  shop.add(purpleBooks)

  var books4 = new THREE.Geometry()
  var book5 = new THREE.BoxGeometry(.7, .75, .2)
  book5.translate(3.75, 3.45, .6)
  books4.merge(book5)
  book5.translate(0, 0, -1)
  books4.merge(book5)
  book5.translate(0, 1, -.75)
  books4.merge(book5)
  book5.translate(0, 0, 1.5)
  books4.merge(book5)
  book5.translate(0, 0, .75)
  books4.merge(book5)
  book5.translate(-7.5, -1, -1.75)
  books4.merge(book5)
  book5.translate(0, -1, -.5)
  books4.merge(book5)
  book5.translate(0, 0, 1.5)
  books4.merge(book5)
  var book6 = new THREE.BoxGeometry(.7, .75, .2)
  book6.translate(3.5, 1.87, 2.25)
  books4.merge(book6)
  var orangeBooks = new THREE.Mesh(books4, orange)
  orangeBooks.castShadow = true
  shop.add(orangeBooks)

  var booksShadows = new THREE.Geometry()
  var redShadows = book1.clone(true)
  booksShadows.merge(redShadows)
  var blueShadows = books2.clone(true)
  booksShadows.merge(blueShadows)
  var purpleShadows = books3.clone(true)
  purpleShadows.translate(-.00, .001, .001)
  booksShadows.merge(purpleShadows)
  var orangeShadows = books4.clone(true)
  booksShadows.merge(orangeShadows)
  var showInteriorShadows = new THREE.Mesh(booksShadows, shadows)
  showInteriorShadows.receiveShadow = true
  shop.add(showInteriorShadows)

// Awning
  // White Stripes
  var awningA = new THREE.Geometry()
  var aA1 = new THREE.BoxGeometry(1.1, 1.25, 2)
  aA1.translate(-4.4, 5.25, 3.5)
  aA1.vertices[0].y-=.9;
  aA1.vertices[5].y-=.9;
  awningA.merge(aA1)
  aA1.translate(2.2, 0, 0)
  awningA.merge(aA1)
  aA1.translate(2.2, 0, 0)
  awningA.merge(aA1)
  aA1.translate(2.2, 0, 0)
  awningA.merge(aA1)
  aA1.translate(2.2, 0, 0)
  awningA.merge(aA1)
  var As = new THREE.Mesh(awningA, offwhite)
  As.castShadow = true
  // Red Stripes
  var awningB = new THREE.Geometry()
  var aB1 = new THREE.BoxGeometry(1.1, 1.25, 2)
  aB1.translate(-3.3, 5.25, 3.5)
  aB1.vertices[0].y-=.9;
  aB1.vertices[5].y-=.9;
  awningB.merge(aB1)
  aB1.translate(2.2, 0, 0)
  awningB.merge(aB1)
  aB1.translate(2.2, 0, 0)
  awningB.merge(aB1)
  aB1.translate(2.2, 0, 0)
  awningB.merge(aB1)
  var Bs = new THREE.Mesh(awningB, blue)
  Bs.castShadow = true
  var awningShadowGeometry = new THREE.Geometry()
  var aShadow = awningA.clone()
  var bShadow = awningB.clone()
  awningShadowGeometry.merge(aShadow)
  awningShadowGeometry.merge(bShadow)
  var awningShadows = new THREE.Mesh(awningShadowGeometry, shadows)
  awningShadows.scale.set(1.01, 1.01, 1.01)
  awningShadows.receiveShadow = true
//  shop.add(awningShadows)
//  shop.add(As)
//  shop.add(Bs)

// Add To Scene
  shop.position.set(0, 1, 0) // 8, -9
  scene.add(shop)

}
